# Generated by Django 5.1.4 on 2024-12-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizsessionquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsession',
            old_name='user_id',
            new_name='user',
        ),
    ]
