# Generated by Django 5.1.4 on 2024-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_userattempt_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='questions_answered_correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='questions_answered_wrong',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
    ]
